2021-02-24 18:17:05,848 INFO: Microblog startup [in /Users/markgetrost/Projects/FlaskMega/firstwebapp/app/__init__.py:52]
2021-02-24 18:36:48,185 ERROR: Exception on /edit_profile [GET] [in /Users/markgetrost/.pyenv/versions/3.9.0/envs/venv390/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/markgetrost/.pyenv/versions/3.9.0/envs/venv390/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/markgetrost/.pyenv/versions/3.9.0/envs/venv390/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/markgetrost/.pyenv/versions/3.9.0/envs/venv390/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/markgetrost/.pyenv/versions/3.9.0/envs/venv390/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/markgetrost/.pyenv/versions/3.9.0/envs/venv390/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/markgetrost/.pyenv/versions/3.9.0/envs/venv390/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/markgetrost/.pyenv/versions/3.9.0/envs/venv390/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/markgetrost/Projects/FlaskMega/firstwebapp/app/routes.py", line 94, in edit_profile
    form = EditProfileForm()
  File "/Users/markgetrost/.pyenv/versions/3.9.0/envs/venv390/lib/python3.9/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2021-02-24 18:36:55,753 ERROR: Exception on /edit_profile [GET] [in /Users/markgetrost/.pyenv/versions/3.9.0/envs/venv390/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/markgetrost/.pyenv/versions/3.9.0/envs/venv390/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/markgetrost/.pyenv/versions/3.9.0/envs/venv390/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/markgetrost/.pyenv/versions/3.9.0/envs/venv390/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/markgetrost/.pyenv/versions/3.9.0/envs/venv390/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/markgetrost/.pyenv/versions/3.9.0/envs/venv390/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/markgetrost/.pyenv/versions/3.9.0/envs/venv390/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/markgetrost/.pyenv/versions/3.9.0/envs/venv390/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/markgetrost/Projects/FlaskMega/firstwebapp/app/routes.py", line 94, in edit_profile
    form = EditProfileForm()
  File "/Users/markgetrost/.pyenv/versions/3.9.0/envs/venv390/lib/python3.9/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
